### ISSUE TITLE
Deserialization does not work with `bincode`

### ISSUE THREAD

**Issue by futile** [magiclen/Byte-Unit#12]
Deserialization of `Byte` uses `Deserializer::deserialize_any()`, which does not work with, e.g., [`bincode`](https://github.com/bincode-org/bincode).

The documentation of `Deserializer::deserialize_any()` ([link](https://docs.rs/serde/1.0.126/serde/trait.Deserializer.html#tymethod.deserialize_any)) notes that:

> When implementing Deserialize, you should avoid relying on Deserializer::deserialize_any unless you need to be told by the Deserializer what type is in the input. Know that relying on Deserializer::deserialize_any means your data type will be able to deserialize from self-describing formats only, ruling out Bincode and many others.

**Comment by magiclen** [comment]
After version 5.0, this crate does not use `Deserializer::deserialize_any()` and it should be compatible with `bincode`.

**Comment by futile** [comment]
Awesome! :) I'm not working on that particular project anymore, so can't say if it's working for me now or not. Thus I'll simply close this issue, and assume it works now :)

Thanks a lot for the reply, even after ~2 years, really cool! :partying_face: And gz on version 5.0 :)
