### ISSUE TITLE
ByteError should implement std::error::Error

### ISSUE THREAD

**Issue by SOF3** [magiclen/Byte-Unit#2]
This allows conversion between error types more easily.

**Comment by magiclen** [comment]
You can enable the `std` feature to let `ByteError` implement `std::error::Error` since `v3.1.0`.

**Comment by SOF3** [comment]
Oh, it's undocumented on docs.rs

**Comment by magiclen** [comment]
Yeah, I know. Because the `std` feature does nothing more than that. It is kind of insignificant.

To be honest, I don't get the gist of `std::error::Error`. Not sure when we should use that.

**Comment by SOF3** [comment]
When you want to wrap it in another enum/trait. When you want to pass it as an error source.

**Comment by magiclen** [comment]
The `std` feature has been in the default features since 4.0.0.
