### ISSUE TITLE
Floating point errors with Byte::from_str()

### ISSUE THREAD

**Issue by chapa** [magiclen/Byte-Unit#6]
Hi,

I noticed that some values cannot be converted from string :
```rust
assert_eq!(
    Byte::from_unit(76.65, ByteUnit::MB).unwrap().get_bytes(),
    Byte::from_str("76.65 MB").unwrap().get_bytes()
);
```
```
thread panicked at 'assertion failed: `(left == right)`
  left: `76650000`,
 right: `76649999`'
```

It's because `Byte::from_str()` does calculations with floats, which can lead to unexpected results :
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f33e0ffe218d5ea7f1c29d7adc98f79f

What do you think of using something like [rust_decimal](https://docs.rs/rust_decimal) ?

**Comment by magiclen** [comment]
After version 5.0, `byte_unit` has integrated `rust_decimal`. 

The following code is working now.

```rust
use std::str::FromStr;

use byte_unit::{Byte, Unit};

fn main() {
    assert_eq!(
        Byte::from_f64_with_unit(76.65, Unit::MB).unwrap().as_u64(),
        Byte::from_str("76.65 MB").unwrap().as_u64()
    );
}
```

**Comment by chapa** [comment]
Nice :+1:
