### ISSUE TITLE
Add const modifier to Byte::from_bytes.

### ISSUE THREAD

**Issue by dacut** [magiclen/Byte-Unit#9]
Since `Byte::from_bytes()` can never fail, it would be great if we could write code like this:

```
const DEFAULT_SIZE: Byte = Byte::from_bytes(1024);
```

This would require having the `const` modifier on the `Byte::from_bytes()` function, though. Could it be added?

Thanks!

**Comment by magiclen** [comment]
Thank you. It's done. #5
